### PR TITLE
Change logic to label videos as HD

### PR DESCRIPTION
**Pull request by muratakbal**
Instead of using bandwith, use resolution tag to decide quality of video

### CODE REVIEW

**Comment by muratakbal** [comment]
@burakbostancioglu can you check this?

**Comment by muratakbal** [comment]
@ivanaslamov can you check this?

**Review by ivanaslamov — APPROVED** [review]
LGTM

**Comment by muratakbal** [comment]
[(1) [HLS] Update video selection algorithm [1]](https://trello.com/c/xt5GjrCE/5250-1-hls-update-video-selection-algorithm-1)

**Comment by burakbostancioglu** [comment]
LGTM

**Pull request merged**
